export class ViewInsurance{
    policyNumber:number=0;
    userFname:string='';
    userMname:string='';
    userLname:string='';
    userEmail:string='';
    userPhone:string='';
    userPhotoIdType:string='';
    userPhotoIdNumber:string='';
    vehicleType:string='';
    vehicleRegistrationNumber:number=0;
    vehicleBrand:string='';
    vehicleModel:string='';
    insuranceType:string='';
    insuranceDuration:string='';
    insuranceStartDate:string='';
    insuranceEndDate:string='';
    insurancePremiumPaid:string='';
    maxAmountInsured:string='';
}